import java.util.ArrayList;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        ArrayList<Postinfo> postinfoer = new ArrayList<>();
        Scanner input = new Scanner(System.in);

        postinfoer.add(new Postinfo(	800	, "	Høje Taastrup	"));
        postinfoer.add(new Postinfo(	900	, "	København C	"));
        postinfoer.add(new Postinfo(	917	, "	Københavns Pakkecent	"));
        postinfoer.add(new Postinfo(	960	, "	Udland	"));
        postinfoer.add(new Postinfo(	999	, "	København C	"));
        postinfoer.add(new Postinfo(	1000	, "	København K	"));
        postinfoer.add(new Postinfo(	1050	, "	København K	"));
        postinfoer.add(new Postinfo(	1051	, "	København K	"));
        postinfoer.add(new Postinfo(	1052	, "	København K	"));
        postinfoer.add(new Postinfo(	1053	, "	København K	"));
        postinfoer.add(new Postinfo(	1054	, "	København K	"));
        postinfoer.add(new Postinfo(	1055	, "	København K	"));
        postinfoer.add(new Postinfo(	1056	, "	København K	"));
        postinfoer.add(new Postinfo(	1057	, "	København K	"));
        postinfoer.add(new Postinfo(	1058	, "	København K	"));
        postinfoer.add(new Postinfo(	1059	, "	København K	"));
        postinfoer.add(new Postinfo(	1060	, "	København K	"));
        postinfoer.add(new Postinfo(	1061	, "	København K	"));
        postinfoer.add(new Postinfo(	1062	, "	København K	"));
        postinfoer.add(new Postinfo(	1063	, "	København K	"));
        postinfoer.add(new Postinfo(	1064	, "	København K	"));
        postinfoer.add(new Postinfo(	1065	, "	København K	"));
        postinfoer.add(new Postinfo(	1066	, "	København K	"));
        postinfoer.add(new Postinfo(	1067	, "	København K	"));
        postinfoer.add(new Postinfo(	1068	, "	København K	"));
        postinfoer.add(new Postinfo(	1069	, "	København K	"));
        postinfoer.add(new Postinfo(	1070	, "	København K	"));
        postinfoer.add(new Postinfo(	1071	, "	København K	"));
        postinfoer.add(new Postinfo(	1072	, "	København K	"));
        postinfoer.add(new Postinfo(	1073	, "	København K	"));
        postinfoer.add(new Postinfo(	1074	, "	København K	"));
        postinfoer.add(new Postinfo(	1092	, "	København K	"));
        postinfoer.add(new Postinfo(	1093	, "	København K	"));
        postinfoer.add(new Postinfo(	1095	, "	København K	"));
        postinfoer.add(new Postinfo(	1098	, "	København K	"));
        postinfoer.add(new Postinfo(	1100	, "	København K	"));
        postinfoer.add(new Postinfo(	1101	, "	København K	"));
        postinfoer.add(new Postinfo(	1102	, "	København K	"));
        postinfoer.add(new Postinfo(	1103	, "	København K	"));
        postinfoer.add(new Postinfo(	1104	, "	København K	"));
        postinfoer.add(new Postinfo(	1105	, "	København K	"));
        postinfoer.add(new Postinfo(	1106	, "	København K	"));
        postinfoer.add(new Postinfo(	1107	, "	København K	"));
        postinfoer.add(new Postinfo(	1110	, "	København K	"));
        postinfoer.add(new Postinfo(	1111	, "	København K	"));
        postinfoer.add(new Postinfo(	1112	, "	København K	"));
        postinfoer.add(new Postinfo(	1113	, "	København K	"));
        postinfoer.add(new Postinfo(	1114	, "	København K	"));
        postinfoer.add(new Postinfo(	1115	, "	København K	"));
        postinfoer.add(new Postinfo(	1116	, "	København K	"));
        postinfoer.add(new Postinfo(	1117	, "	København K	"));
        postinfoer.add(new Postinfo(	1118	, "	København K	"));
        postinfoer.add(new Postinfo(	1119	, "	København K	"));
        postinfoer.add(new Postinfo(	1120	, "	København K	"));
        postinfoer.add(new Postinfo(	1121	, "	København K	"));
        postinfoer.add(new Postinfo(	1122	, "	København K	"));
        postinfoer.add(new Postinfo(	1123	, "	København K	"));
        postinfoer.add(new Postinfo(	1124	, "	København K	"));
        postinfoer.add(new Postinfo(	1125	, "	København K	"));
        postinfoer.add(new Postinfo(	1126	, "	København K	"));
        postinfoer.add(new Postinfo(	1127	, "	København K	"));
        postinfoer.add(new Postinfo(	1128	, "	København K	"));
        postinfoer.add(new Postinfo(	1129	, "	København K	"));
        postinfoer.add(new Postinfo(	1130	, "	København K	"));
        postinfoer.add(new Postinfo(	1131	, "	København K	"));
        postinfoer.add(new Postinfo(	1140	, "	København K	"));
        postinfoer.add(new Postinfo(	1147	, "	København K	"));
        postinfoer.add(new Postinfo(	1148	, "	København K	"));
        postinfoer.add(new Postinfo(	1150	, "	København K	"));
        postinfoer.add(new Postinfo(	1151	, "	København K	"));
        postinfoer.add(new Postinfo(	1152	, "	København K	"));
        postinfoer.add(new Postinfo(	1153	, "	København K	"));
        postinfoer.add(new Postinfo(	1154	, "	København K	"));
        postinfoer.add(new Postinfo(	1155	, "	København K	"));
        postinfoer.add(new Postinfo(	1156	, "	København K	"));
        postinfoer.add(new Postinfo(	1157	, "	København K	"));
        postinfoer.add(new Postinfo(	1158	, "	København K	"));
        postinfoer.add(new Postinfo(	1159	, "	København K	"));
        postinfoer.add(new Postinfo(	1160	, "	København K	"));
        postinfoer.add(new Postinfo(	1161	, "	København K	"));
        postinfoer.add(new Postinfo(	1162	, "	København K	"));
        postinfoer.add(new Postinfo(	1164	, "	København K	"));
        postinfoer.add(new Postinfo(	1165	, "	København K	"));
        postinfoer.add(new Postinfo(	1166	, "	København K	"));
        postinfoer.add(new Postinfo(	1167	, "	København K	"));
        postinfoer.add(new Postinfo(	1168	, "	København K	"));
        postinfoer.add(new Postinfo(	1169	, "	København K	"));
        postinfoer.add(new Postinfo(	1170	, "	København K	"));
        postinfoer.add(new Postinfo(	1171	, "	København K	"));
        postinfoer.add(new Postinfo(	1172	, "	København K	"));
        postinfoer.add(new Postinfo(	1173	, "	København K	"));
        postinfoer.add(new Postinfo(	1174	, "	København K	"));
        postinfoer.add(new Postinfo(	1175	, "	København K	"));
        postinfoer.add(new Postinfo(	1200	, "	København K	"));
        postinfoer.add(new Postinfo(	1201	, "	København K	"));
        postinfoer.add(new Postinfo(	1202	, "	København K	"));
        postinfoer.add(new Postinfo(	1203	, "	København K	"));
        postinfoer.add(new Postinfo(	1204	, "	København K	"));
        postinfoer.add(new Postinfo(	1205	, "	København K	"));
        postinfoer.add(new Postinfo(	1206	, "	København K	"));
        postinfoer.add(new Postinfo(	1207	, "	København K	"));
        postinfoer.add(new Postinfo(	1208	, "	København K	"));
        postinfoer.add(new Postinfo(	1209	, "	København K	"));
        postinfoer.add(new Postinfo(	1210	, "	København K	"));
        postinfoer.add(new Postinfo(	1211	, "	København K	"));
        postinfoer.add(new Postinfo(	1213	, "	København K	"));
        postinfoer.add(new Postinfo(	1214	, "	København K	"));
        postinfoer.add(new Postinfo(	1215	, "	København K	"));
        postinfoer.add(new Postinfo(	1216	, "	København K	"));
        postinfoer.add(new Postinfo(	1217	, "	København K	"));
        postinfoer.add(new Postinfo(	1218	, "	København K	"));
        postinfoer.add(new Postinfo(	1219	, "	København K	"));
        postinfoer.add(new Postinfo(	1220	, "	København K	"));
        postinfoer.add(new Postinfo(	1221	, "	København K	"));
        postinfoer.add(new Postinfo(	1240	, "	København K	"));
        postinfoer.add(new Postinfo(	1250	, "	København K	"));
        postinfoer.add(new Postinfo(	1251	, "	København K	"));
        postinfoer.add(new Postinfo(	1253	, "	København K	"));
        postinfoer.add(new Postinfo(	1254	, "	København K	"));
        postinfoer.add(new Postinfo(	1255	, "	København K	"));
        postinfoer.add(new Postinfo(	1256	, "	København K	"));
        postinfoer.add(new Postinfo(	1257	, "	København K	"));
        postinfoer.add(new Postinfo(	1259	, "	København K	"));
        postinfoer.add(new Postinfo(	1260	, "	København K	"));
        postinfoer.add(new Postinfo(	1261	, "	København K	"));
        postinfoer.add(new Postinfo(	1263	, "	København K	"));
        postinfoer.add(new Postinfo(	1264	, "	København K	"));
        postinfoer.add(new Postinfo(	1265	, "	København K	"));
        postinfoer.add(new Postinfo(	1266	, "	København K	"));
        postinfoer.add(new Postinfo(	1267	, "	København K	"));
        postinfoer.add(new Postinfo(	1268	, "	København K	"));
        postinfoer.add(new Postinfo(	1270	, "	København K	"));
        postinfoer.add(new Postinfo(	1271	, "	København K	"));
        postinfoer.add(new Postinfo(	1291	, "	København K	"));
        postinfoer.add(new Postinfo(	1300	, "	København K	"));
        postinfoer.add(new Postinfo(	1301	, "	København K	"));
        postinfoer.add(new Postinfo(	1302	, "	København K	"));
        postinfoer.add(new Postinfo(	1303	, "	København K	"));
        postinfoer.add(new Postinfo(	1304	, "	København K	"));
        postinfoer.add(new Postinfo(	1306	, "	København K	"));
        postinfoer.add(new Postinfo(	1307	, "	København K	"));
        postinfoer.add(new Postinfo(	1308	, "	København K	"));
        postinfoer.add(new Postinfo(	1309	, "	København K	"));
        postinfoer.add(new Postinfo(	1310	, "	København K	"));
        postinfoer.add(new Postinfo(	1311	, "	København K	"));
        postinfoer.add(new Postinfo(	1312	, "	København K	"));
        postinfoer.add(new Postinfo(	1313	, "	København K	"));
        postinfoer.add(new Postinfo(	1314	, "	København K	"));
        postinfoer.add(new Postinfo(	1315	, "	København K	"));
        postinfoer.add(new Postinfo(	1316	, "	København K	"));
        postinfoer.add(new Postinfo(	1317	, "	København K	"));
        postinfoer.add(new Postinfo(	1318	, "	København K	"));
        postinfoer.add(new Postinfo(	1319	, "	København K	"));
        postinfoer.add(new Postinfo(	1320	, "	København K	"));
        postinfoer.add(new Postinfo(	1321	, "	København K	"));
        postinfoer.add(new Postinfo(	1322	, "	København K	"));
        postinfoer.add(new Postinfo(	1323	, "	København K	"));
        postinfoer.add(new Postinfo(	1324	, "	København K	"));
        postinfoer.add(new Postinfo(	1325	, "	København K	"));
        postinfoer.add(new Postinfo(	1326	, "	København K	"));
        postinfoer.add(new Postinfo(	1327	, "	København K	"));
        postinfoer.add(new Postinfo(	1328	, "	København K	"));
        postinfoer.add(new Postinfo(	1329	, "	København K	"));
        postinfoer.add(new Postinfo(	1350	, "	København K	"));
        postinfoer.add(new Postinfo(	1352	, "	København K	"));
        postinfoer.add(new Postinfo(	1353	, "	København K	"));
        postinfoer.add(new Postinfo(	1354	, "	København K	"));
        postinfoer.add(new Postinfo(	1355	, "	København K	"));
        postinfoer.add(new Postinfo(	1356	, "	København K	"));
        postinfoer.add(new Postinfo(	1357	, "	København K	"));
        postinfoer.add(new Postinfo(	1358	, "	København K	"));
        postinfoer.add(new Postinfo(	1359	, "	København K	"));
        postinfoer.add(new Postinfo(	1360	, "	København K	"));
        postinfoer.add(new Postinfo(	1361	, "	København K	"));
        postinfoer.add(new Postinfo(	1362	, "	København K	"));
        postinfoer.add(new Postinfo(	1363	, "	København K	"));
        postinfoer.add(new Postinfo(	1364	, "	København K	"));
        postinfoer.add(new Postinfo(	1365	, "	København K	"));
        postinfoer.add(new Postinfo(	1366	, "	København K	"));
        postinfoer.add(new Postinfo(	1367	, "	København K	"));
        postinfoer.add(new Postinfo(	1368	, "	København K	"));
        postinfoer.add(new Postinfo(	1369	, "	København K	"));
        postinfoer.add(new Postinfo(	1370	, "	København K	"));
        postinfoer.add(new Postinfo(	1371	, "	København K	"));
        postinfoer.add(new Postinfo(	1400	, "	København K	"));
        postinfoer.add(new Postinfo(	1401	, "	København K	"));
        postinfoer.add(new Postinfo(	1402	, "	København K	"));
        postinfoer.add(new Postinfo(	1403	, "	København K	"));
        postinfoer.add(new Postinfo(	1406	, "	København K	"));
        postinfoer.add(new Postinfo(	1407	, "	København K	"));
        postinfoer.add(new Postinfo(	1408	, "	København K	"));
        postinfoer.add(new Postinfo(	1409	, "	København K	"));
        postinfoer.add(new Postinfo(	1410	, "	København K	"));
        postinfoer.add(new Postinfo(	1411	, "	København K	"));
        postinfoer.add(new Postinfo(	1412	, "	København K	"));
        postinfoer.add(new Postinfo(	1413	, "	København K	"));
        postinfoer.add(new Postinfo(	1414	, "	København K	"));
        postinfoer.add(new Postinfo(	1415	, "	København K	"));
        postinfoer.add(new Postinfo(	1416	, "	København K	"));
        postinfoer.add(new Postinfo(	1417	, "	København K	"));
        postinfoer.add(new Postinfo(	1418	, "	København K	"));
        postinfoer.add(new Postinfo(	1419	, "	København K	"));
        postinfoer.add(new Postinfo(	1420	, "	København K	"));
        postinfoer.add(new Postinfo(	1421	, "	København K	"));
        postinfoer.add(new Postinfo(	1422	, "	København K	"));
        postinfoer.add(new Postinfo(	1423	, "	København K	"));
        postinfoer.add(new Postinfo(	1424	, "	København K	"));
        postinfoer.add(new Postinfo(	1425	, "	København K	"));
        postinfoer.add(new Postinfo(	1426	, "	København K	"));
        postinfoer.add(new Postinfo(	1427	, "	København K	"));
        postinfoer.add(new Postinfo(	1428	, "	København K	"));
        postinfoer.add(new Postinfo(	1429	, "	København K	"));
        postinfoer.add(new Postinfo(	1430	, "	København K	"));
        postinfoer.add(new Postinfo(	1431	, "	København K	"));
        postinfoer.add(new Postinfo(	1432	, "	København K	"));
        postinfoer.add(new Postinfo(	1433	, "	København K	"));
        postinfoer.add(new Postinfo(	1434	, "	København K	"));
        postinfoer.add(new Postinfo(	1435	, "	København K	"));
        postinfoer.add(new Postinfo(	1436	, "	København K	"));
        postinfoer.add(new Postinfo(	1437	, "	København K	"));
        postinfoer.add(new Postinfo(	1438	, "	København K	"));
        postinfoer.add(new Postinfo(	1439	, "	København K	"));
        postinfoer.add(new Postinfo(	1440	, "	København K	"));
        postinfoer.add(new Postinfo(	1441	, "	København K	"));
        postinfoer.add(new Postinfo(	1448	, "	København K	"));
        postinfoer.add(new Postinfo(	1450	, "	København K	"));
        postinfoer.add(new Postinfo(	1451	, "	København K	"));
        postinfoer.add(new Postinfo(	1452	, "	København K	"));
        postinfoer.add(new Postinfo(	1453	, "	København K	"));
        postinfoer.add(new Postinfo(	1454	, "	København K	"));
        postinfoer.add(new Postinfo(	1455	, "	København K	"));
        postinfoer.add(new Postinfo(	1456	, "	København K	"));
        postinfoer.add(new Postinfo(	1457	, "	København K	"));
        postinfoer.add(new Postinfo(	1458	, "	København K	"));
        postinfoer.add(new Postinfo(	1459	, "	København K	"));
        postinfoer.add(new Postinfo(	1460	, "	København K	"));
        postinfoer.add(new Postinfo(	1462	, "	København K	"));
        postinfoer.add(new Postinfo(	1463	, "	København K	"));
        postinfoer.add(new Postinfo(	1464	, "	København K	"));
        postinfoer.add(new Postinfo(	1466	, "	København K	"));
        postinfoer.add(new Postinfo(	1467	, "	København K	"));
        postinfoer.add(new Postinfo(	1468	, "	København K	"));
        postinfoer.add(new Postinfo(	1470	, "	København K	"));
        postinfoer.add(new Postinfo(	1471	, "	København K	"));
        postinfoer.add(new Postinfo(	1472	, "	København K	"));
        postinfoer.add(new Postinfo(	1500	, "	København V	"));
        postinfoer.add(new Postinfo(	1513	, "	Centraltastning	"));
        postinfoer.add(new Postinfo(	1532	, "	København V	"));
        postinfoer.add(new Postinfo(	1533	, "	København V	"));
        postinfoer.add(new Postinfo(	1550	, "	København V	"));
        postinfoer.add(new Postinfo(	1551	, "	København V	"));
        postinfoer.add(new Postinfo(	1552	, "	København V	"));
        postinfoer.add(new Postinfo(	1553	, "	København V	"));
        postinfoer.add(new Postinfo(	1554	, "	København V	"));
        postinfoer.add(new Postinfo(	1555	, "	København V	"));
        postinfoer.add(new Postinfo(	1556	, "	København V	"));
        postinfoer.add(new Postinfo(	1557	, "	København V	"));
        postinfoer.add(new Postinfo(	1558	, "	København V	"));
        postinfoer.add(new Postinfo(	1559	, "	København V	"));
        postinfoer.add(new Postinfo(	1560	, "	København V	"));
        postinfoer.add(new Postinfo(	1561	, "	København V	"));
        postinfoer.add(new Postinfo(	1562	, "	København V	"));
        postinfoer.add(new Postinfo(	1563	, "	København V	"));
        postinfoer.add(new Postinfo(	1564	, "	København V	"));
        postinfoer.add(new Postinfo(	1566	, "	København V	"));
        postinfoer.add(new Postinfo(	1567	, "	København V	"));
        postinfoer.add(new Postinfo(	1568	, "	København V	"));
        postinfoer.add(new Postinfo(	1569	, "	København V	"));
        postinfoer.add(new Postinfo(	1570	, "	København V	"));
        postinfoer.add(new Postinfo(	1571	, "	København V	"));
        postinfoer.add(new Postinfo(	1572	, "	København V	"));
        postinfoer.add(new Postinfo(	1573	, "	København V	"));
        postinfoer.add(new Postinfo(	1574	, "	København V	"));
        postinfoer.add(new Postinfo(	1575	, "	København V	"));
        postinfoer.add(new Postinfo(	1576	, "	København V	"));
        postinfoer.add(new Postinfo(	1577	, "	København V	"));
        postinfoer.add(new Postinfo(	1592	, "	København V	"));
        postinfoer.add(new Postinfo(	1599	, "	København V	"));
        postinfoer.add(new Postinfo(	1600	, "	København V	"));
        postinfoer.add(new Postinfo(	1601	, "	København V	"));
        postinfoer.add(new Postinfo(	1602	, "	København V	"));
        postinfoer.add(new Postinfo(	1603	, "	København V	"));
        postinfoer.add(new Postinfo(	1604	, "	København V	"));
        postinfoer.add(new Postinfo(	1606	, "	København V	"));
        postinfoer.add(new Postinfo(	1607	, "	København V	"));
        postinfoer.add(new Postinfo(	1608	, "	København V	"));
        postinfoer.add(new Postinfo(	1609	, "	København V	"));
        postinfoer.add(new Postinfo(	1610	, "	København V	"));
        postinfoer.add(new Postinfo(	1611	, "	København V	"));
        postinfoer.add(new Postinfo(	1612	, "	København V	"));
        postinfoer.add(new Postinfo(	1613	, "	København V	"));
        postinfoer.add(new Postinfo(	1614	, "	København V	"));
        postinfoer.add(new Postinfo(	1615	, "	København V	"));
        postinfoer.add(new Postinfo(	1616	, "	København V	"));
        postinfoer.add(new Postinfo(	1617	, "	København V	"));
        postinfoer.add(new Postinfo(	1618	, "	København V	"));
        postinfoer.add(new Postinfo(	1619	, "	København V	"));
        postinfoer.add(new Postinfo(	1620	, "	København V	"));
        postinfoer.add(new Postinfo(	1621	, "	København V	"));
        postinfoer.add(new Postinfo(	1622	, "	København V	"));
        postinfoer.add(new Postinfo(	1623	, "	København V	"));
        postinfoer.add(new Postinfo(	1624	, "	København V	"));
        postinfoer.add(new Postinfo(	1630	, "	København V	"));
        postinfoer.add(new Postinfo(	1631	, "	København V	"));
        postinfoer.add(new Postinfo(	1632	, "	København V	"));
        postinfoer.add(new Postinfo(	1633	, "	København V	"));
        postinfoer.add(new Postinfo(	1634	, "	København V	"));
        postinfoer.add(new Postinfo(	1635	, "	København V	"));
        postinfoer.add(new Postinfo(	1650	, "	København V	"));
        postinfoer.add(new Postinfo(	1651	, "	København V	"));
        postinfoer.add(new Postinfo(	1652	, "	København V	"));
        postinfoer.add(new Postinfo(	1653	, "	København V	"));
        postinfoer.add(new Postinfo(	1654	, "	København V	"));
        postinfoer.add(new Postinfo(	1655	, "	København V	"));
        postinfoer.add(new Postinfo(	1656	, "	København V	"));
        postinfoer.add(new Postinfo(	1657	, "	København V	"));
        postinfoer.add(new Postinfo(	1658	, "	København V	"));
        postinfoer.add(new Postinfo(	1659	, "	København V	"));
        postinfoer.add(new Postinfo(	1660	, "	København V	"));
        postinfoer.add(new Postinfo(	1661	, "	København V	"));
        postinfoer.add(new Postinfo(	1662	, "	København V	"));
        postinfoer.add(new Postinfo(	1663	, "	København V	"));
        postinfoer.add(new Postinfo(	1664	, "	København V	"));
        postinfoer.add(new Postinfo(	1665	, "	København V	"));
        postinfoer.add(new Postinfo(	1666	, "	København V	"));
        postinfoer.add(new Postinfo(	1667	, "	København V	"));
        postinfoer.add(new Postinfo(	1668	, "	København V	"));
        postinfoer.add(new Postinfo(	1669	, "	København V	"));
        postinfoer.add(new Postinfo(	1670	, "	København V	"));
        postinfoer.add(new Postinfo(	1671	, "	København V	"));
        postinfoer.add(new Postinfo(	1672	, "	København V	"));
        postinfoer.add(new Postinfo(	1673	, "	København V	"));
        postinfoer.add(new Postinfo(	1674	, "	København V	"));
        postinfoer.add(new Postinfo(	1675	, "	København V	"));
        postinfoer.add(new Postinfo(	1676	, "	København V	"));
        postinfoer.add(new Postinfo(	1677	, "	København V	"));
        postinfoer.add(new Postinfo(	1699	, "	København V	"));
        postinfoer.add(new Postinfo(	1700	, "	København V	"));
        postinfoer.add(new Postinfo(	1701	, "	København V	"));
        postinfoer.add(new Postinfo(	1702	, "	København V	"));
        postinfoer.add(new Postinfo(	1703	, "	København V	"));
        postinfoer.add(new Postinfo(	1704	, "	København V	"));
        postinfoer.add(new Postinfo(	1705	, "	København V	"));
        postinfoer.add(new Postinfo(	1706	, "	København V	"));
        postinfoer.add(new Postinfo(	1707	, "	København V	"));
        postinfoer.add(new Postinfo(	1708	, "	København V	"));
        postinfoer.add(new Postinfo(	1709	, "	København V	"));
        postinfoer.add(new Postinfo(	1710	, "	København V	"));
        postinfoer.add(new Postinfo(	1711	, "	København V	"));
        postinfoer.add(new Postinfo(	1712	, "	København V	"));
        postinfoer.add(new Postinfo(	1714	, "	København V	"));
        postinfoer.add(new Postinfo(	1715	, "	København V	"));
        postinfoer.add(new Postinfo(	1716	, "	København V	"));
        postinfoer.add(new Postinfo(	1717	, "	København V	"));
        postinfoer.add(new Postinfo(	1718	, "	København V	"));
        postinfoer.add(new Postinfo(	1719	, "	København V	"));
        postinfoer.add(new Postinfo(	1720	, "	København V	"));
        postinfoer.add(new Postinfo(	1721	, "	København V	"));
        postinfoer.add(new Postinfo(	1722	, "	København V	"));
        postinfoer.add(new Postinfo(	1723	, "	København V	"));
        postinfoer.add(new Postinfo(	1724	, "	København V	"));
        postinfoer.add(new Postinfo(	1725	, "	København V	"));
        postinfoer.add(new Postinfo(	1726	, "	København V	"));
        postinfoer.add(new Postinfo(	1727	, "	København V	"));
        postinfoer.add(new Postinfo(	1728	, "	København V	"));
        postinfoer.add(new Postinfo(	1729	, "	København V	"));
        postinfoer.add(new Postinfo(	1730	, "	København V	"));
        postinfoer.add(new Postinfo(	1731	, "	København V	"));
        postinfoer.add(new Postinfo(	1732	, "	København V	"));
        postinfoer.add(new Postinfo(	1733	, "	København V	"));
        postinfoer.add(new Postinfo(	1734	, "	København V	"));
        postinfoer.add(new Postinfo(	1735	, "	København V	"));
        postinfoer.add(new Postinfo(	1736	, "	København V	"));
        postinfoer.add(new Postinfo(	1737	, "	København V	"));
        postinfoer.add(new Postinfo(	1738	, "	København V	"));
        postinfoer.add(new Postinfo(	1739	, "	København V	"));
        postinfoer.add(new Postinfo(	1749	, "	København V	"));
        postinfoer.add(new Postinfo(	1750	, "	København V	"));
        postinfoer.add(new Postinfo(	1751	, "	København V	"));
        postinfoer.add(new Postinfo(	1752	, "	København V	"));
        postinfoer.add(new Postinfo(	1753	, "	København V	"));
        postinfoer.add(new Postinfo(	1754	, "	København V	"));
        postinfoer.add(new Postinfo(	1755	, "	København V	"));
        postinfoer.add(new Postinfo(	1756	, "	København V	"));
        postinfoer.add(new Postinfo(	1757	, "	København V	"));
        postinfoer.add(new Postinfo(	1758	, "	København V	"));
        postinfoer.add(new Postinfo(	1759	, "	København V	"));
        postinfoer.add(new Postinfo(	1760	, "	København V	"));
        postinfoer.add(new Postinfo(	1761	, "	København V	"));
        postinfoer.add(new Postinfo(	1762	, "	København V	"));
        postinfoer.add(new Postinfo(	1763	, "	København V	"));
        postinfoer.add(new Postinfo(	1764	, "	København V	"));
        postinfoer.add(new Postinfo(	1765	, "	København V	"));
        postinfoer.add(new Postinfo(	1766	, "	København V	"));
        postinfoer.add(new Postinfo(	1770	, "	København V	"));
        postinfoer.add(new Postinfo(	1771	, "	København V	"));
        postinfoer.add(new Postinfo(	1772	, "	København V	"));
        postinfoer.add(new Postinfo(	1773	, "	København V	"));
        postinfoer.add(new Postinfo(	1774	, "	København V	"));
        postinfoer.add(new Postinfo(	1775	, "	København V	"));
        postinfoer.add(new Postinfo(	1777	, "	København V	"));
        postinfoer.add(new Postinfo(	1780	, "	København V	"));
        postinfoer.add(new Postinfo(	1785	, "	København V	"));
        postinfoer.add(new Postinfo(	1786	, "	København V	"));
        postinfoer.add(new Postinfo(	1787	, "	København V	"));
        postinfoer.add(new Postinfo(	1790	, "	København V	"));
        postinfoer.add(new Postinfo(	1799	, "	København V	"));
        postinfoer.add(new Postinfo(	1800	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1801	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1802	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1803	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1804	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1805	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1806	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1807	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1808	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1809	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1810	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1811	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1812	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1813	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1814	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1815	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1816	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1817	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1818	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1819	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1820	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1822	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1823	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1824	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1825	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1826	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1827	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1828	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1829	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1850	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1851	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1852	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1853	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1854	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1855	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1856	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1857	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1860	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1861	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1862	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1863	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1864	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1865	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1866	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1867	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1868	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1870	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1871	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1872	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1873	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1874	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1875	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1876	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1877	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1878	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1879	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1900	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1901	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1902	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1903	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1904	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1905	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1906	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1908	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1909	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1910	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1911	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1912	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1913	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1914	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1915	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1916	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1917	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1920	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1921	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1922	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1923	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1924	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1925	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1926	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1927	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1928	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1950	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1951	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1952	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1953	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1954	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1955	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1956	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1957	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1958	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1959	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1960	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1961	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1962	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1963	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1964	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1965	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1966	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1967	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1970	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1971	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1972	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1973	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	1974	, "	Frederiksberg C	"));
        postinfoer.add(new Postinfo(	2000	, "	Frederiksberg	"));
        postinfoer.add(new Postinfo(	2100	, "	København Ø	"));
        postinfoer.add(new Postinfo(	2150	, "	Nordhavn	"));
        postinfoer.add(new Postinfo(	2200	, "	København N	"));
        postinfoer.add(new Postinfo(	2300	, "	København S	"));
        postinfoer.add(new Postinfo(	2400	, "	København NV	"));
        postinfoer.add(new Postinfo(	2450	, "	København SV	"));
        postinfoer.add(new Postinfo(	2500	, "	Valby	"));
        postinfoer.add(new Postinfo(	2600	, "	Glostrup	"));
        postinfoer.add(new Postinfo(	2605	, "	Brøndby	"));
        postinfoer.add(new Postinfo(	2610	, "	Rødovre	"));
        postinfoer.add(new Postinfo(	2620	, "	Albertslund	"));
        postinfoer.add(new Postinfo(	2625	, "	Vallensbæk	"));
        postinfoer.add(new Postinfo(	2630	, "	Taastrup	"));
        postinfoer.add(new Postinfo(	2635	, "	Ishøj	"));
        postinfoer.add(new Postinfo(	2640	, "	Hedehusene	"));
        postinfoer.add(new Postinfo(	2650	, "	Hvidovre	"));
        postinfoer.add(new Postinfo(	2660	, "	Brøndby Strand	"));
        postinfoer.add(new Postinfo(	2665	, "	Vallensbæk Strand	"));
        postinfoer.add(new Postinfo(	2670	, "	Greve	"));
        postinfoer.add(new Postinfo(	2680	, "	Solrød Strand	"));
        postinfoer.add(new Postinfo(	2690	, "	Karlslunde	"));
        postinfoer.add(new Postinfo(	2700	, "	Brønshøj	"));
        postinfoer.add(new Postinfo(	2720	, "	Vanløse	"));
        postinfoer.add(new Postinfo(	2730	, "	Herlev	"));
        postinfoer.add(new Postinfo(	2740	, "	Skovlunde	"));
        postinfoer.add(new Postinfo(	2750	, "	Ballerup	"));
        postinfoer.add(new Postinfo(	2760	, "	Måløv	"));
        postinfoer.add(new Postinfo(	2765	, "	Smørum	"));
        postinfoer.add(new Postinfo(	2770	, "	Kastrup	"));
        postinfoer.add(new Postinfo(	2791	, "	Dragør	"));
        postinfoer.add(new Postinfo(	2800	, "	Kongens Lyngby	"));
        postinfoer.add(new Postinfo(	2820	, "	Gentofte	"));
        postinfoer.add(new Postinfo(	2830	, "	Virum	"));
        postinfoer.add(new Postinfo(	2840	, "	Holte	"));
        postinfoer.add(new Postinfo(	2850	, "	Nærum	"));
        postinfoer.add(new Postinfo(	2860	, "	Søborg	"));
        postinfoer.add(new Postinfo(	2870	, "	Dyssegård	"));
        postinfoer.add(new Postinfo(	2880	, "	Bagsværd	"));
        postinfoer.add(new Postinfo(	2900	, "	Hellerup	"));
        postinfoer.add(new Postinfo(	2920	, "	Charlottenlund	"));
        postinfoer.add(new Postinfo(	2930	, "	Klampenborg	"));
        postinfoer.add(new Postinfo(	2942	, "	Skodsborg	"));
        postinfoer.add(new Postinfo(	2950	, "	Vedbæk	"));
        postinfoer.add(new Postinfo(	2960	, "	Rungsted Kyst	"));
        postinfoer.add(new Postinfo(	2970	, "	Hørsholm	"));
        postinfoer.add(new Postinfo(	2980	, "	Kokkedal	"));
        postinfoer.add(new Postinfo(	2990	, "	Nivå	"));
        postinfoer.add(new Postinfo(	3000	, "	Helsingør	"));
        postinfoer.add(new Postinfo(	3050	, "	Humlebæk	"));
        postinfoer.add(new Postinfo(	3060	, "	Espergærde	"));
        postinfoer.add(new Postinfo(	3070	, "	Snekkersten	"));
        postinfoer.add(new Postinfo(	3080	, "	Tikøb	"));
        postinfoer.add(new Postinfo(	3100	, "	Hornbæk	"));
        postinfoer.add(new Postinfo(	3120	, "	Dronningmølle	"));
        postinfoer.add(new Postinfo(	3140	, "	Ålsgårde	"));
        postinfoer.add(new Postinfo(	3150	, "	Hellebæk	"));
        postinfoer.add(new Postinfo(	3200	, "	Helsinge	"));
        postinfoer.add(new Postinfo(	3210	, "	Vejby	"));
        postinfoer.add(new Postinfo(	3220	, "	Tisvildeleje	"));
        postinfoer.add(new Postinfo(	3230	, "	Græsted	"));
        postinfoer.add(new Postinfo(	3250	, "	Gilleleje	"));
        postinfoer.add(new Postinfo(	3300	, "	Frederiksværk	"));
        postinfoer.add(new Postinfo(	3310	, "	Ølsted	"));
        postinfoer.add(new Postinfo(	3320	, "	Skævinge	"));
        postinfoer.add(new Postinfo(	3330	, "	Gørløse	"));
        postinfoer.add(new Postinfo(	3360	, "	Liseleje	"));
        postinfoer.add(new Postinfo(	3370	, "	Melby	"));
        postinfoer.add(new Postinfo(	3390	, "	Hundested	"));
        postinfoer.add(new Postinfo(	3400	, "	Hillerød	"));
        postinfoer.add(new Postinfo(	3450	, "	Allerød	"));
        postinfoer.add(new Postinfo(	3460	, "	Birkerød	"));
        postinfoer.add(new Postinfo(	3480	, "	Fredensborg	"));
        postinfoer.add(new Postinfo(	3490	, "	Kvistgård	"));
        postinfoer.add(new Postinfo(	3500	, "	Værløse	"));
        postinfoer.add(new Postinfo(	3520	, "	Farum	"));
        postinfoer.add(new Postinfo(	3540	, "	Lynge	"));
        postinfoer.add(new Postinfo(	3550	, "	Slangerup	"));
        postinfoer.add(new Postinfo(	3600	, "	Frederikssund	"));
        postinfoer.add(new Postinfo(	3630	, "	Jægerspris	"));
        postinfoer.add(new Postinfo(	3650	, "	Ølstykke	"));
        postinfoer.add(new Postinfo(	3660	, "	Stenløse	"));
        postinfoer.add(new Postinfo(	3670	, "	Veksø Sjælland	"));
        postinfoer.add(new Postinfo(	3700	, "	Rønne	"));
        postinfoer.add(new Postinfo(	3720	, "	Aakirkeby	"));
        postinfoer.add(new Postinfo(	3730	, "	Nexø	"));
        postinfoer.add(new Postinfo(	3740	, "	Svaneke	"));
        postinfoer.add(new Postinfo(	3751	, "	Østermarie	"));
        postinfoer.add(new Postinfo(	3760	, "	Gudhjem	"));
        postinfoer.add(new Postinfo(	3770	, "	Allinge	"));
        postinfoer.add(new Postinfo(	3782	, "	Klemensker	"));
        postinfoer.add(new Postinfo(	3790	, "	Hasle	"));
        postinfoer.add(new Postinfo(	4000	, "	Roskilde	"));
        postinfoer.add(new Postinfo(	4030	, "	Tune	"));
        postinfoer.add(new Postinfo(	4040	, "	Jyllinge	"));
        postinfoer.add(new Postinfo(	4050	, "	Skibby	"));
        postinfoer.add(new Postinfo(	4060	, "	Kirke Såby	"));
        postinfoer.add(new Postinfo(	4070	, "	Kirke Hyllinge	"));
        postinfoer.add(new Postinfo(	4100	, "	Ringsted	"));
        postinfoer.add(new Postinfo(	4130	, "	Viby Sjælland	"));
        postinfoer.add(new Postinfo(	4140	, "	Borup	"));
        postinfoer.add(new Postinfo(	4160	, "	Herlufmagle	"));
        postinfoer.add(new Postinfo(	4171	, "	Glumsø	"));
        postinfoer.add(new Postinfo(	4173	, "	Fjenneslev	"));
        postinfoer.add(new Postinfo(	4174	, "	Jystrup Midtsj	"));
        postinfoer.add(new Postinfo(	4180	, "	Sorø	"));
        postinfoer.add(new Postinfo(	4190	, "	Munke Bjergby	"));
        postinfoer.add(new Postinfo(	4200	, "	Slagelse	"));
        postinfoer.add(new Postinfo(	4220	, "	Korsør	"));
        postinfoer.add(new Postinfo(	4230	, "	Skælskør	"));
        postinfoer.add(new Postinfo(	4241	, "	Vemmelev	"));
        postinfoer.add(new Postinfo(	4242	, "	Boeslunde	"));
        postinfoer.add(new Postinfo(	4243	, "	Rude	"));
        postinfoer.add(new Postinfo(	4250	, "	Fuglebjerg	"));
        postinfoer.add(new Postinfo(	4261	, "	Dalmose	"));
        postinfoer.add(new Postinfo(	4262	, "	Sandved	"));
        postinfoer.add(new Postinfo(	4270	, "	Høng	"));
        postinfoer.add(new Postinfo(	4281	, "	Gørlev	"));
        postinfoer.add(new Postinfo(	4291	, "	Ruds Vedby	"));
        postinfoer.add(new Postinfo(	4293	, "	Dianalund	"));
        postinfoer.add(new Postinfo(	4295	, "	Stenlille	"));
        postinfoer.add(new Postinfo(	4296	, "	Nyrup	"));
        postinfoer.add(new Postinfo(	4300	, "	Holbæk	"));
        postinfoer.add(new Postinfo(	4320	, "	Lejre	"));
        postinfoer.add(new Postinfo(	4330	, "	Hvalsø	"));
        postinfoer.add(new Postinfo(	4340	, "	Tølløse	"));
        postinfoer.add(new Postinfo(	4350	, "	Ugerløse	"));
        postinfoer.add(new Postinfo(	4360	, "	Kirke Eskilstrup	"));
        postinfoer.add(new Postinfo(	4370	, "	Store Merløse	"));
        postinfoer.add(new Postinfo(	4390	, "	Vipperød	"));
        postinfoer.add(new Postinfo(	4400	, "	Kalundborg	"));
        postinfoer.add(new Postinfo(	4420	, "	Regstrup	"));
        postinfoer.add(new Postinfo(	4440	, "	Mørkøv	"));
        postinfoer.add(new Postinfo(	4450	, "	Jyderup	"));
        postinfoer.add(new Postinfo(	4460	, "	Snertinge	"));
        postinfoer.add(new Postinfo(	4470	, "	Svebølle	"));
        postinfoer.add(new Postinfo(	4480	, "	Store Fuglede	"));
        postinfoer.add(new Postinfo(	4490	, "	Jerslev Sjælland	"));
        postinfoer.add(new Postinfo(	4500	, "	Nykøbing Sj	"));
        postinfoer.add(new Postinfo(	4520	, "	Svinninge	"));
        postinfoer.add(new Postinfo(	4532	, "	Gislinge	"));
        postinfoer.add(new Postinfo(	4534	, "	Hørve	"));
        postinfoer.add(new Postinfo(	4540	, "	Fårevejle	"));
        postinfoer.add(new Postinfo(	4550	, "	Asnæs	"));
        postinfoer.add(new Postinfo(	4560	, "	Vig	"));
        postinfoer.add(new Postinfo(	4571	, "	Grevinge	"));
        postinfoer.add(new Postinfo(	4572	, "	Nørre Asmindrup	"));
        postinfoer.add(new Postinfo(	4573	, "	Højby	"));
        postinfoer.add(new Postinfo(	4581	, "	Rørvig	"));
        postinfoer.add(new Postinfo(	4583	, "	Sjællands Odde	"));
        postinfoer.add(new Postinfo(	4591	, "	Føllenslev	"));
        postinfoer.add(new Postinfo(	4592	, "	Sejerø	"));
        postinfoer.add(new Postinfo(	4593	, "	Eskebjerg	"));
        postinfoer.add(new Postinfo(	4600	, "	Køge	"));
        postinfoer.add(new Postinfo(	4621	, "	Gadstrup	"));
        postinfoer.add(new Postinfo(	4622	, "	Havdrup	"));
        postinfoer.add(new Postinfo(	4623	, "	Lille Skensved	"));
        postinfoer.add(new Postinfo(	4632	, "	Bjæverskov	"));
        postinfoer.add(new Postinfo(	4640	, "	Faxe	"));
        postinfoer.add(new Postinfo(	4652	, "	Hårlev	"));
        postinfoer.add(new Postinfo(	4653	, "	Karise	"));
        postinfoer.add(new Postinfo(	4654	, "	Faxe Ladeplads	"));
        postinfoer.add(new Postinfo(	4660	, "	Store Heddinge	"));
        postinfoer.add(new Postinfo(	4671	, "	Strøby	"));
        postinfoer.add(new Postinfo(	4672	, "	Klippinge	"));
        postinfoer.add(new Postinfo(	4673	, "	Rødvig Stevns	"));
        postinfoer.add(new Postinfo(	4681	, "	Herfølge	"));
        postinfoer.add(new Postinfo(	4682	, "	Tureby	"));
        postinfoer.add(new Postinfo(	4683	, "	Rønnede	"));
        postinfoer.add(new Postinfo(	4684	, "	Holmegaard	"));
        postinfoer.add(new Postinfo(	4690	, "	Haslev	"));
        postinfoer.add(new Postinfo(	4700	, "	Næstved	"));
        postinfoer.add(new Postinfo(	4720	, "	Præstø	"));
        postinfoer.add(new Postinfo(	4733	, "	Tappernøje	"));
        postinfoer.add(new Postinfo(	4735	, "	Mern	"));
        postinfoer.add(new Postinfo(	4736	, "	Karrebæksminde	"));
        postinfoer.add(new Postinfo(	4750	, "	Lundby	"));
        postinfoer.add(new Postinfo(	4760	, "	Vordingborg	"));
        postinfoer.add(new Postinfo(	4771	, "	Kalvehave	"));
        postinfoer.add(new Postinfo(	4772	, "	Langebæk	"));
        postinfoer.add(new Postinfo(	4773	, "	Stensved	"));
        postinfoer.add(new Postinfo(	4780	, "	Stege	"));
        postinfoer.add(new Postinfo(	4791	, "	Borre	"));
        postinfoer.add(new Postinfo(	4792	, "	Askeby	"));
        postinfoer.add(new Postinfo(	4793	, "	Bogø By	"));
        postinfoer.add(new Postinfo(	4800	, "	Nykøbing F	"));
        postinfoer.add(new Postinfo(	4840	, "	Nørre Alslev	"));
        postinfoer.add(new Postinfo(	4850	, "	Stubbekøbing	"));
        postinfoer.add(new Postinfo(	4862	, "	Guldborg	"));
        postinfoer.add(new Postinfo(	4863	, "	Eskilstrup	"));
        postinfoer.add(new Postinfo(	4871	, "	Horbelev	"));
        postinfoer.add(new Postinfo(	4872	, "	Idestrup	"));
        postinfoer.add(new Postinfo(	4873	, "	Væggerløse	"));
        postinfoer.add(new Postinfo(	4874	, "	Gedser	"));
        postinfoer.add(new Postinfo(	4880	, "	Nysted	"));
        postinfoer.add(new Postinfo(	4891	, "	Toreby L	"));
        postinfoer.add(new Postinfo(	4892	, "	Kettinge	"));
        postinfoer.add(new Postinfo(	4894	, "	Øster Ulslev	"));
        postinfoer.add(new Postinfo(	4895	, "	Errindlev	"));
        postinfoer.add(new Postinfo(	4900	, "	Nakskov	"));
        postinfoer.add(new Postinfo(	4912	, "	Harpelunde	"));
        postinfoer.add(new Postinfo(	4913	, "	Horslunde	"));
        postinfoer.add(new Postinfo(	4920	, "	Søllested	"));
        postinfoer.add(new Postinfo(	4930	, "	Maribo	"));
        postinfoer.add(new Postinfo(	4941	, "	Bandholm	"));
        postinfoer.add(new Postinfo(	4943	, "	Torrig L	"));
        postinfoer.add(new Postinfo(	4944	, "	Fejø	"));
        postinfoer.add(new Postinfo(	4951	, "	Nørreballe	"));
        postinfoer.add(new Postinfo(	4952	, "	Stokkemarke	"));
        postinfoer.add(new Postinfo(	4953	, "	Vesterborg	"));
        postinfoer.add(new Postinfo(	4960	, "	Holeby	"));
        postinfoer.add(new Postinfo(	4970	, "	Rødby	"));
        postinfoer.add(new Postinfo(	4983	, "	Dannemare	"));
        postinfoer.add(new Postinfo(	4990	, "	Sakskøbing	"));
        postinfoer.add(new Postinfo(	5000	, "	Odense C	"));
        postinfoer.add(new Postinfo(	5200	, "	Odense V	"));
        postinfoer.add(new Postinfo(	5210	, "	Odense NV	"));
        postinfoer.add(new Postinfo(	5220	, "	Odense SØ	"));
        postinfoer.add(new Postinfo(	5230	, "	Odense M	"));
        postinfoer.add(new Postinfo(	5240	, "	Odense NØ	"));
        postinfoer.add(new Postinfo(	5250	, "	Odense SV	"));
        postinfoer.add(new Postinfo(	5260	, "	Odense S	"));
        postinfoer.add(new Postinfo(	5270	, "	Odense N	"));
        postinfoer.add(new Postinfo(	5290	, "	Marslev	"));
        postinfoer.add(new Postinfo(	5300	, "	Kerteminde	"));
        postinfoer.add(new Postinfo(	5320	, "	Agedrup	"));
        postinfoer.add(new Postinfo(	5330	, "	Munkebo	"));
        postinfoer.add(new Postinfo(	5350	, "	Rynkeby	"));
        postinfoer.add(new Postinfo(	5370	, "	Mesinge	"));
        postinfoer.add(new Postinfo(	5380	, "	Dalby	"));
        postinfoer.add(new Postinfo(	5390	, "	Martofte	"));
        postinfoer.add(new Postinfo(	5400	, "	Bogense	"));
        postinfoer.add(new Postinfo(	5450	, "	Otterup	"));
        postinfoer.add(new Postinfo(	5462	, "	Morud	"));
        postinfoer.add(new Postinfo(	5463	, "	Harndrup	"));
        postinfoer.add(new Postinfo(	5464	, "	Brenderup Fyn	"));
        postinfoer.add(new Postinfo(	5466	, "	Asperup	"));
        postinfoer.add(new Postinfo(	5471	, "	Søndersø	"));
        postinfoer.add(new Postinfo(	5474	, "	Veflinge	"));
        postinfoer.add(new Postinfo(	5485	, "	Skamby	"));
        postinfoer.add(new Postinfo(	5491	, "	Blommenslyst	"));
        postinfoer.add(new Postinfo(	5492	, "	Vissenbjerg	"));
        postinfoer.add(new Postinfo(	5500	, "	Middelfart	"));
        postinfoer.add(new Postinfo(	5540	, "	Ullerslev	"));
        postinfoer.add(new Postinfo(	5550	, "	Langeskov	"));
        postinfoer.add(new Postinfo(	5560	, "	Aarup	"));
        postinfoer.add(new Postinfo(	5580	, "	Nørre Aaby	"));
        postinfoer.add(new Postinfo(	5591	, "	Gelsted	"));
        postinfoer.add(new Postinfo(	5592	, "	Ejby	"));
        postinfoer.add(new Postinfo(	5600	, "	Faaborg	"));
        postinfoer.add(new Postinfo(	5610	, "	Assens	"));
        postinfoer.add(new Postinfo(	5620	, "	Glamsbjerg	"));
        postinfoer.add(new Postinfo(	5631	, "	Ebberup	"));
        postinfoer.add(new Postinfo(	5642	, "	Millinge	"));
        postinfoer.add(new Postinfo(	5672	, "	Broby	"));
        postinfoer.add(new Postinfo(	5683	, "	Haarby	"));
        postinfoer.add(new Postinfo(	5690	, "	Tommerup	"));
        postinfoer.add(new Postinfo(	5700	, "	Svendborg	"));
        postinfoer.add(new Postinfo(	5750	, "	Ringe	"));
        postinfoer.add(new Postinfo(	5762	, "	Vester Skerninge	"));
        postinfoer.add(new Postinfo(	5771	, "	Stenstrup	"));
        postinfoer.add(new Postinfo(	5772	, "	Kværndrup	"));
        postinfoer.add(new Postinfo(	5792	, "	Årslev	"));
        postinfoer.add(new Postinfo(	5800	, "	Nyborg	"));
        postinfoer.add(new Postinfo(	5853	, "	Ørbæk	"));
        postinfoer.add(new Postinfo(	5854	, "	Gislev	"));
        postinfoer.add(new Postinfo(	5856	, "	Ryslinge	"));
        postinfoer.add(new Postinfo(	5863	, "	Ferritslev Fyn	"));
        postinfoer.add(new Postinfo(	5871	, "	Frørup	"));
        postinfoer.add(new Postinfo(	5874	, "	Hesselager	"));
        postinfoer.add(new Postinfo(	5881	, "	Skårup Fyn	"));
        postinfoer.add(new Postinfo(	5882	, "	Vejstrup	"));
        postinfoer.add(new Postinfo(	5883	, "	Oure	"));
        postinfoer.add(new Postinfo(	5884	, "	Gudme	"));
        postinfoer.add(new Postinfo(	5892	, "	Gudbjerg Sydfyn	"));
        postinfoer.add(new Postinfo(	5900	, "	Rudkøbing	"));
        postinfoer.add(new Postinfo(	5932	, "	Humble	"));
        postinfoer.add(new Postinfo(	5935	, "	Bagenkop	"));
        postinfoer.add(new Postinfo(	5953	, "	Tranekær	"));
        postinfoer.add(new Postinfo(	5960	, "	Marstal	"));
        postinfoer.add(new Postinfo(	5970	, "	Ærøskøbing	"));
        postinfoer.add(new Postinfo(	5985	, "	Søby Ærø	"));
        postinfoer.add(new Postinfo(	6000	, "	Kolding	"));
        postinfoer.add(new Postinfo(	6040	, "	Egtved	"));
        postinfoer.add(new Postinfo(	6051	, "	Almind	"));
        postinfoer.add(new Postinfo(	6052	, "	Viuf	"));
        postinfoer.add(new Postinfo(	6064	, "	Jordrup	"));
        postinfoer.add(new Postinfo(	6070	, "	Christiansfeld	"));
        postinfoer.add(new Postinfo(	6091	, "	Bjert	"));
        postinfoer.add(new Postinfo(	6092	, "	Sønder Stenderup	"));
        postinfoer.add(new Postinfo(	6093	, "	Sjølund	"));
        postinfoer.add(new Postinfo(	6094	, "	Hejls	"));
        postinfoer.add(new Postinfo(	6100	, "	Haderslev	"));
        postinfoer.add(new Postinfo(	6200	, "	Aabenraa	"));
        postinfoer.add(new Postinfo(	6230	, "	Rødekro	"));
        postinfoer.add(new Postinfo(	6240	, "	Løgumkloster	"));
        postinfoer.add(new Postinfo(	6261	, "	Bredebro	"));
        postinfoer.add(new Postinfo(	6270	, "	Tønder	"));
        postinfoer.add(new Postinfo(	6280	, "	Højer	"));
        postinfoer.add(new Postinfo(	6300	, "	Gråsten	"));
        postinfoer.add(new Postinfo(	6310	, "	Broager	"));
        postinfoer.add(new Postinfo(	6320	, "	Egernsund	"));
        postinfoer.add(new Postinfo(	6330	, "	Padborg	"));
        postinfoer.add(new Postinfo(	6340	, "	Kruså	"));
        postinfoer.add(new Postinfo(	6360	, "	Tinglev	"));
        postinfoer.add(new Postinfo(	6372	, "	Bylderup-Bov	"));
        postinfoer.add(new Postinfo(	6392	, "	Bolderslev	"));
        postinfoer.add(new Postinfo(	6400	, "	Sønderborg	"));
        postinfoer.add(new Postinfo(	6430	, "	Nordborg	"));
        postinfoer.add(new Postinfo(	6440	, "	Augustenborg	"));
        postinfoer.add(new Postinfo(	6470	, "	Sydals	"));
        postinfoer.add(new Postinfo(	6500	, "	Vojens	"));
        postinfoer.add(new Postinfo(	6510	, "	Gram	"));
        postinfoer.add(new Postinfo(	6520	, "	Toftlund	"));
        postinfoer.add(new Postinfo(	6534	, "	Agerskov	"));
        postinfoer.add(new Postinfo(	6535	, "	Branderup J	"));
        postinfoer.add(new Postinfo(	6541	, "	Bevtoft	"));
        postinfoer.add(new Postinfo(	6560	, "	Sommersted	"));
        postinfoer.add(new Postinfo(	6580	, "	Vamdrup	"));
        postinfoer.add(new Postinfo(	6600	, "	Vejen	"));
        postinfoer.add(new Postinfo(	6621	, "	Gesten	"));
        postinfoer.add(new Postinfo(	6622	, "	Bække	"));
        postinfoer.add(new Postinfo(	6623	, "	Vorbasse	"));
        postinfoer.add(new Postinfo(	6630	, "	Rødding	"));
        postinfoer.add(new Postinfo(	6640	, "	Lunderskov	"));
        postinfoer.add(new Postinfo(	6650	, "	Brørup	"));
        postinfoer.add(new Postinfo(	6660	, "	Lintrup	"));
        postinfoer.add(new Postinfo(	6670	, "	Holsted	"));
        postinfoer.add(new Postinfo(	6682	, "	Hovborg	"));
        postinfoer.add(new Postinfo(	6683	, "	Føvling	"));
        postinfoer.add(new Postinfo(	6690	, "	Gørding	"));
        postinfoer.add(new Postinfo(	6700	, "	Esbjerg	"));
        postinfoer.add(new Postinfo(	6705	, "	Esbjerg Ø	"));
        postinfoer.add(new Postinfo(	6710	, "	Esbjerg V	"));
        postinfoer.add(new Postinfo(	6715	, "	Esbjerg N	"));
        postinfoer.add(new Postinfo(	6720	, "	Fanø	"));
        postinfoer.add(new Postinfo(	6731	, "	Tjæreborg	"));
        postinfoer.add(new Postinfo(	6740	, "	Bramming	"));
        postinfoer.add(new Postinfo(	6752	, "	Glejbjerg	"));
        postinfoer.add(new Postinfo(	6753	, "	Agerbæk	"));
        postinfoer.add(new Postinfo(	6760	, "	Ribe	"));
        postinfoer.add(new Postinfo(	6771	, "	Gredstedbro	"));
        postinfoer.add(new Postinfo(	6780	, "	Skærbæk	"));
        postinfoer.add(new Postinfo(	6792	, "	Rømø	"));
        postinfoer.add(new Postinfo(	6800	, "	Varde	"));
        postinfoer.add(new Postinfo(	6818	, "	Årre	"));
        postinfoer.add(new Postinfo(	6823	, "	Ansager	"));
        postinfoer.add(new Postinfo(	6830	, "	Nørre Nebel	"));
        postinfoer.add(new Postinfo(	6840	, "	Oksbøl	"));
        postinfoer.add(new Postinfo(	6851	, "	Janderup Vestj	"));
        postinfoer.add(new Postinfo(	6852	, "	Billum	"));
        postinfoer.add(new Postinfo(	6853	, "	Vejers Strand	"));
        postinfoer.add(new Postinfo(	6854	, "	Henne	"));
        postinfoer.add(new Postinfo(	6855	, "	Outrup	"));
        postinfoer.add(new Postinfo(	6857	, "	Blåvand	"));
        postinfoer.add(new Postinfo(	6862	, "	Tistrup	"));
        postinfoer.add(new Postinfo(	6870	, "	Ølgod	"));
        postinfoer.add(new Postinfo(	6880	, "	Tarm	"));
        postinfoer.add(new Postinfo(	6893	, "	Hemmet	"));
        postinfoer.add(new Postinfo(	6900	, "	Skjern	"));
        postinfoer.add(new Postinfo(	6920	, "	Videbæk	"));
        postinfoer.add(new Postinfo(	6933	, "	Kibæk	"));
        postinfoer.add(new Postinfo(	6940	, "	Lem St	"));
        postinfoer.add(new Postinfo(	6950	, "	Ringkøbing	"));
        postinfoer.add(new Postinfo(	6960	, "	Hvide Sande	"));
        postinfoer.add(new Postinfo(	6971	, "	Spjald	"));
        postinfoer.add(new Postinfo(	6973	, "	Ørnhøj	"));
        postinfoer.add(new Postinfo(	6980	, "	Tim	"));
        postinfoer.add(new Postinfo(	6990	, "	Ulfborg	"));
        postinfoer.add(new Postinfo(	7000	, "	Fredericia	"));
        postinfoer.add(new Postinfo(	7007	, "	Fredericia	"));
        postinfoer.add(new Postinfo(	7080	, "	Børkop	"));
        postinfoer.add(new Postinfo(	7100	, "	Vejle	"));
        postinfoer.add(new Postinfo(	7120	, "	Vejle Øst	"));
        postinfoer.add(new Postinfo(	7130	, "	Juelsminde	"));
        postinfoer.add(new Postinfo(	7140	, "	Stouby	"));
        postinfoer.add(new Postinfo(	7150	, "	Barrit	"));
        postinfoer.add(new Postinfo(	7160	, "	Tørring	"));
        postinfoer.add(new Postinfo(	7171	, "	Uldum	"));
        postinfoer.add(new Postinfo(	7173	, "	Vonge	"));
        postinfoer.add(new Postinfo(	7182	, "	Bredsten	"));
        postinfoer.add(new Postinfo(	7183	, "	Randbøl	"));
        postinfoer.add(new Postinfo(	7184	, "	Vandel	"));
        postinfoer.add(new Postinfo(	7190	, "	Billund	"));
        postinfoer.add(new Postinfo(	7200	, "	Grindsted	"));
        postinfoer.add(new Postinfo(	7250	, "	Hejnsvig	"));
        postinfoer.add(new Postinfo(	7260	, "	Sønder Omme	"));
        postinfoer.add(new Postinfo(	7270	, "	Stakroge	"));
        postinfoer.add(new Postinfo(	7280	, "	Sønder Felding	"));
        postinfoer.add(new Postinfo(	7300	, "	Jelling	"));
        postinfoer.add(new Postinfo(	7321	, "	Gadbjerg	"));
        postinfoer.add(new Postinfo(	7323	, "	Give	"));
        postinfoer.add(new Postinfo(	7330	, "	Brande	"));
        postinfoer.add(new Postinfo(	7361	, "	Ejstrupholm	"));
        postinfoer.add(new Postinfo(	7362	, "	Hampen	"));
        postinfoer.add(new Postinfo(	7400	, "	Herning	"));
        postinfoer.add(new Postinfo(	7430	, "	Ikast	"));
        postinfoer.add(new Postinfo(	7441	, "	Bording	"));
        postinfoer.add(new Postinfo(	7442	, "	Engesvang	"));
        postinfoer.add(new Postinfo(	7451	, "	Sunds	"));
        postinfoer.add(new Postinfo(	7470	, "	Karup J	"));
        postinfoer.add(new Postinfo(	7480	, "	Vildbjerg	"));
        postinfoer.add(new Postinfo(	7490	, "	Aulum	"));
        postinfoer.add(new Postinfo(	7500	, "	Holstebro	"));
        postinfoer.add(new Postinfo(	7540	, "	Haderup	"));
        postinfoer.add(new Postinfo(	7550	, "	Sørvad	"));
        postinfoer.add(new Postinfo(	7560	, "	Hjerm	"));
        postinfoer.add(new Postinfo(	7570	, "	Vemb	"));
        postinfoer.add(new Postinfo(	7600	, "	Struer	"));
        postinfoer.add(new Postinfo(	7620	, "	Lemvig	"));
        postinfoer.add(new Postinfo(	7650	, "	Bøvlingbjerg	"));
        postinfoer.add(new Postinfo(	7660	, "	Bækmarksbro	"));
        postinfoer.add(new Postinfo(	7673	, "	Harboøre	"));
        postinfoer.add(new Postinfo(	7680	, "	Thyborøn	"));
        postinfoer.add(new Postinfo(	7700	, "	Thisted	"));
        postinfoer.add(new Postinfo(	7730	, "	Hanstholm	"));
        postinfoer.add(new Postinfo(	7741	, "	Frøstrup	"));
        postinfoer.add(new Postinfo(	7742	, "	Vesløs	"));
        postinfoer.add(new Postinfo(	7752	, "	Snedsted	"));
        postinfoer.add(new Postinfo(	7755	, "	Bedsted Thy	"));
        postinfoer.add(new Postinfo(	7760	, "	Hurup Thy	"));
        postinfoer.add(new Postinfo(	7770	, "	Vestervig	"));
        postinfoer.add(new Postinfo(	7790	, "	Thyholm	"));
        postinfoer.add(new Postinfo(	7800	, "	Skive	"));
        postinfoer.add(new Postinfo(	7830	, "	Vinderup	"));
        postinfoer.add(new Postinfo(	7840	, "	Højslev	"));
        postinfoer.add(new Postinfo(	7850	, "	Stoholm Jyll	"));
        postinfoer.add(new Postinfo(	7860	, "	Spøttrup	"));
        postinfoer.add(new Postinfo(	7870	, "	Roslev	"));
        postinfoer.add(new Postinfo(	7884	, "	Fur	"));
        postinfoer.add(new Postinfo(	7900	, "	Nykøbing M	"));
        postinfoer.add(new Postinfo(	7950	, "	Erslev	"));
        postinfoer.add(new Postinfo(	7960	, "	Karby	"));
        postinfoer.add(new Postinfo(	7970	, "	Redsted M	"));
        postinfoer.add(new Postinfo(	7980	, "	Vils	"));
        postinfoer.add(new Postinfo(	7990	, "	Øster Assels	"));
        postinfoer.add(new Postinfo(	8000	, "	Aarhus C	"));
        postinfoer.add(new Postinfo(	8200	, "	Aarhus N	"));
        postinfoer.add(new Postinfo(	8210	, "	Aarhus V	"));
        postinfoer.add(new Postinfo(	8220	, "	Brabrand	"));
        postinfoer.add(new Postinfo(	8230	, "	Åbyhøj	"));
        postinfoer.add(new Postinfo(	8240	, "	Risskov	"));
        postinfoer.add(new Postinfo(	8245	, "	Risskov Ø	"));
        postinfoer.add(new Postinfo(	8250	, "	Egå	"));
        postinfoer.add(new Postinfo(	8260	, "	Viby J	"));
        postinfoer.add(new Postinfo(	8270	, "	Højbjerg	"));
        postinfoer.add(new Postinfo(	8300	, "	Odder	"));
        postinfoer.add(new Postinfo(	8305	, "	Samsø	"));
        postinfoer.add(new Postinfo(	8310	, "	Tranbjerg J	"));
        postinfoer.add(new Postinfo(	8320	, "	Mårslet	"));
        postinfoer.add(new Postinfo(	8330	, "	Beder	"));
        postinfoer.add(new Postinfo(	8340	, "	Malling	"));
        postinfoer.add(new Postinfo(	8350	, "	Hundslund	"));
        postinfoer.add(new Postinfo(	8355	, "	Solbjerg	"));
        postinfoer.add(new Postinfo(	8361	, "	Hasselager	"));
        postinfoer.add(new Postinfo(	8362	, "	Hørning	"));
        postinfoer.add(new Postinfo(	8370	, "	Hadsten	"));
        postinfoer.add(new Postinfo(	8380	, "	Trige	"));
        postinfoer.add(new Postinfo(	8381	, "	Tilst	"));
        postinfoer.add(new Postinfo(	8382	, "	Hinnerup	"));
        postinfoer.add(new Postinfo(	8400	, "	Ebeltoft	"));
        postinfoer.add(new Postinfo(	8410	, "	Rønde	"));
        postinfoer.add(new Postinfo(	8420	, "	Knebel	"));
        postinfoer.add(new Postinfo(	8444	, "	Balle	"));
        postinfoer.add(new Postinfo(	8450	, "	Hammel	"));
        postinfoer.add(new Postinfo(	8462	, "	Harlev J	"));
        postinfoer.add(new Postinfo(	8464	, "	Galten	"));
        postinfoer.add(new Postinfo(	8471	, "	Sabro	"));
        postinfoer.add(new Postinfo(	8472	, "	Sporup	"));
        postinfoer.add(new Postinfo(	8500	, "	Grenaa	"));
        postinfoer.add(new Postinfo(	8520	, "	Lystrup	"));
        postinfoer.add(new Postinfo(	8530	, "	Hjortshøj	"));
        postinfoer.add(new Postinfo(	8541	, "	Skødstrup	"));
        postinfoer.add(new Postinfo(	8543	, "	Hornslet	"));
        postinfoer.add(new Postinfo(	8544	, "	Mørke	"));
        postinfoer.add(new Postinfo(	8550	, "	Ryomgård	"));
        postinfoer.add(new Postinfo(	8560	, "	Kolind	"));
        postinfoer.add(new Postinfo(	8570	, "	Trustrup	"));
        postinfoer.add(new Postinfo(	8581	, "	Nimtofte	"));
        postinfoer.add(new Postinfo(	8585	, "	Glesborg	"));
        postinfoer.add(new Postinfo(	8586	, "	Ørum Djurs	"));
        postinfoer.add(new Postinfo(	8592	, "	Anholt	"));
        postinfoer.add(new Postinfo(	8600	, "	Silkeborg	"));
        postinfoer.add(new Postinfo(	8620	, "	Kjellerup	"));
        postinfoer.add(new Postinfo(	8632	, "	Lemming	"));
        postinfoer.add(new Postinfo(	8641	, "	Sorring	"));
        postinfoer.add(new Postinfo(	8643	, "	Ans By	"));
        postinfoer.add(new Postinfo(	8653	, "	Them	"));
        postinfoer.add(new Postinfo(	8654	, "	Bryrup	"));
        postinfoer.add(new Postinfo(	8660	, "	Skanderborg	"));
        postinfoer.add(new Postinfo(	8670	, "	Låsby	"));
        postinfoer.add(new Postinfo(	8680	, "	Ry	"));
        postinfoer.add(new Postinfo(	8700	, "	Horsens	"));
        postinfoer.add(new Postinfo(	8721	, "	Daugård	"));
        postinfoer.add(new Postinfo(	8722	, "	Hedensted	"));
        postinfoer.add(new Postinfo(	8723	, "	Løsning	"));
        postinfoer.add(new Postinfo(	8732	, "	Hovedgård	"));
        postinfoer.add(new Postinfo(	8740	, "	Brædstrup	"));
        postinfoer.add(new Postinfo(	8751	, "	Gedved	"));
        postinfoer.add(new Postinfo(	8752	, "	Østbirk	"));
        postinfoer.add(new Postinfo(	8762	, "	Flemming	"));
        postinfoer.add(new Postinfo(	8763	, "	Rask Mølle	"));
        postinfoer.add(new Postinfo(	8765	, "	Klovborg	"));
        postinfoer.add(new Postinfo(	8766	, "	Nørre Snede	"));
        postinfoer.add(new Postinfo(	8781	, "	Stenderup	"));
        postinfoer.add(new Postinfo(	8783	, "	Hornsyld	"));
        postinfoer.add(new Postinfo(	8800	, "	Viborg	"));
        postinfoer.add(new Postinfo(	8830	, "	Tjele	"));
        postinfoer.add(new Postinfo(	8831	, "	Løgstrup	"));
        postinfoer.add(new Postinfo(	8832	, "	Skals	"));
        postinfoer.add(new Postinfo(	8840	, "	Rødkærsbro	"));
        postinfoer.add(new Postinfo(	8850	, "	Bjerringbro	"));
        postinfoer.add(new Postinfo(	8860	, "	Ulstrup	"));
        postinfoer.add(new Postinfo(	8870	, "	Langå	"));
        postinfoer.add(new Postinfo(	8881	, "	Thorsø	"));
        postinfoer.add(new Postinfo(	8882	, "	Fårvang	"));
        postinfoer.add(new Postinfo(	8883	, "	Gjern	"));
        postinfoer.add(new Postinfo(	8900	, "	Randers C	"));
        postinfoer.add(new Postinfo(	8920	, "	Randers NV	"));
        postinfoer.add(new Postinfo(	8930	, "	Randers NØ	"));
        postinfoer.add(new Postinfo(	8940	, "	Randers SV	"));
        postinfoer.add(new Postinfo(	8950	, "	Ørsted	"));
        postinfoer.add(new Postinfo(	8960	, "	Randers SØ	"));
        postinfoer.add(new Postinfo(	8961	, "	Allingåbro	"));
        postinfoer.add(new Postinfo(	8963	, "	Auning	"));
        postinfoer.add(new Postinfo(	8970	, "	Havndal	"));
        postinfoer.add(new Postinfo(	8981	, "	Spentrup	"));
        postinfoer.add(new Postinfo(	8983	, "	Gjerlev J	"));
        postinfoer.add(new Postinfo(	8990	, "	Fårup	"));
        postinfoer.add(new Postinfo(	9000	, "	Aalborg	"));
        postinfoer.add(new Postinfo(	9200	, "	Aalborg SV	"));
        postinfoer.add(new Postinfo(	9210	, "	Aalborg SØ	"));
        postinfoer.add(new Postinfo(	9220	, "	Aalborg Øst	"));
        postinfoer.add(new Postinfo(	9230	, "	Svenstrup J	"));
        postinfoer.add(new Postinfo(	9240	, "	Nibe	"));
        postinfoer.add(new Postinfo(	9260	, "	Gistrup	"));
        postinfoer.add(new Postinfo(	9270	, "	Klarup	"));
        postinfoer.add(new Postinfo(	9280	, "	Storvorde	"));
        postinfoer.add(new Postinfo(	9293	, "	Kongerslev	"));
        postinfoer.add(new Postinfo(	9300	, "	Sæby	"));
        postinfoer.add(new Postinfo(	9310	, "	Vodskov	"));
        postinfoer.add(new Postinfo(	9320	, "	Hjallerup	"));
        postinfoer.add(new Postinfo(	9330	, "	Dronninglund	"));
        postinfoer.add(new Postinfo(	9340	, "	Asaa	"));
        postinfoer.add(new Postinfo(	9352	, "	Dybvad	"));
        postinfoer.add(new Postinfo(	9362	, "	Gandrup	"));
        postinfoer.add(new Postinfo(	9370	, "	Hals	"));
        postinfoer.add(new Postinfo(	9380	, "	Vestbjerg	"));
        postinfoer.add(new Postinfo(	9381	, "	Sulsted	"));
        postinfoer.add(new Postinfo(	9382	, "	Tylstrup	"));
        postinfoer.add(new Postinfo(	9400	, "	Nørresundby	"));
        postinfoer.add(new Postinfo(	9430	, "	Vadum	"));
        postinfoer.add(new Postinfo(	9440	, "	Aabybro	"));
        postinfoer.add(new Postinfo(	9460	, "	Brovst	"));
        postinfoer.add(new Postinfo(	9480	, "	Løkken	"));
        postinfoer.add(new Postinfo(	9490	, "	Pandrup	"));
        postinfoer.add(new Postinfo(	9492	, "	Blokhus	"));
        postinfoer.add(new Postinfo(	9493	, "	Saltum	"));
        postinfoer.add(new Postinfo(	9500	, "	Hobro	"));
        postinfoer.add(new Postinfo(	9510	, "	Arden	"));
        postinfoer.add(new Postinfo(	9520	, "	Skørping	"));
        postinfoer.add(new Postinfo(	9530	, "	Støvring	"));
        postinfoer.add(new Postinfo(	9541	, "	Suldrup	"));
        postinfoer.add(new Postinfo(	9550	, "	Mariager	"));
        postinfoer.add(new Postinfo(	9560	, "	Hadsund	"));
        postinfoer.add(new Postinfo(	9574	, "	Bælum	"));
        postinfoer.add(new Postinfo(	9575	, "	Terndrup	"));
        postinfoer.add(new Postinfo(	9600	, "	Aars	"));
        postinfoer.add(new Postinfo(	9610	, "	Nørager	"));
        postinfoer.add(new Postinfo(	9620	, "	Aalestrup	"));
        postinfoer.add(new Postinfo(	9631	, "	Gedsted	"));
        postinfoer.add(new Postinfo(	9632	, "	Møldrup	"));
        postinfoer.add(new Postinfo(	9640	, "	Farsø	"));
        postinfoer.add(new Postinfo(	9670	, "	Løgstør	"));
        postinfoer.add(new Postinfo(	9681	, "	Ranum	"));
        postinfoer.add(new Postinfo(	9690	, "	Fjerritslev	"));
        postinfoer.add(new Postinfo(	9700	, "	Brønderslev	"));
        postinfoer.add(new Postinfo(	9740	, "	Jerslev J	"));
        postinfoer.add(new Postinfo(	9750	, "	Østervrå	"));
        postinfoer.add(new Postinfo(	9760	, "	Vrå	"));
        postinfoer.add(new Postinfo(	9800	, "	Hjørring	"));
        postinfoer.add(new Postinfo(	9830	, "	Tårs	"));
        postinfoer.add(new Postinfo(	9850	, "	Hirtshals	"));
        postinfoer.add(new Postinfo(	9870	, "	Sindal	"));
        postinfoer.add(new Postinfo(	9881	, "	Bindslev	"));
        postinfoer.add(new Postinfo(	9900	, "	Frederikshavn	"));
        postinfoer.add(new Postinfo(	9940	, "	Læsø	"));
        postinfoer.add(new Postinfo(	9970	, "	Strandby	"));
        postinfoer.add(new Postinfo(	9981	, "	Jerup	"));
        postinfoer.add(new Postinfo(	9982	, "	Ålbæk	"));
        postinfoer.add(new Postinfo(	9990	, "	Skagen	"));

        boolean loop = true;

        System.out.println("Indtast 0 for at afslutte programmet");
        while (loop) {
            System.out.print("Indtast postnummer for at finde byen der matcher postnummeret: ");
            int postnr = input.nextInt();

            if (postnr == 0) loop = false;

            for (Postinfo postinfo : postinfoer) {
                if (postinfo.getPostnummer() == postnr)
                    System.out.println(postinfo.getBy());
            }

        }
    }
}
